//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 5/31/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawStopButton:(CGPoint)location;

@end
